[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile.cpu"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[variables]
PYTHONUNBUFFERED = "1"
PYTHONPATH = "/app/python"
HOST = "0.0.0.0"
PORT = "$PORT"