// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kpiyskhvdjoyfuipipzf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtwaXlza2h2ZGpveWZ1aXBpcHpmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1ODcyNTMsImV4cCI6MjA3MDE2MzI1M30.3h_S7u3NhMfUZIj3XsYUz7V6UI4PgcObx-mM1n-P4Bs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});